### ISSUE TITLE
featured product title isn't centered.

### ISSUE THREAD

**Issue by drunkhacker** [easi6/homepage#3]
in small size window, it looks okay, but when the web browser get large, it goes down.

see attached.

![2015-07-23 16 57 48](https://cloud.githubusercontent.com/assets/461823/8845676/111b41a0-315c-11e5-9fa8-a3cd00f85004.png)
![2015-07-23 16 57 21](https://cloud.githubusercontent.com/assets/461823/8845677/114c3990-315c-11e5-8b54-a300ac02981e.png)

**Comment by spica** [comment]
#news 
max-height: 800px; << this is the problem. 

add "max-height:800px" to #bgvid 
or remove max-height:800px at #news

**Comment by d4rekanguok** [comment]
removed max-height at #news, to-do:make body wrapper with restricted max-width
