### ISSUE TITLE
평창 서비스 예약하기 버튼 링크 수정

### ISSUE THREAD

**Issue by spica** [easi6/homepage#5]
지금 
http://www.pyeongchangservice.com  으로 연결되어 있어서 그냥 Hello world로 보임. 
nginx 리다이렉트 설정하든지 
http://pyeongchangservice.com/web/booking 로 바꿔야 할 듯

**Comment by drunkhacker** [comment]
https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md

**Comment by drunkhacker** [comment]
해결함

pyeongchangservice.com을 pyeongchangcarservice.com으로 리디렉트함
